"use strict";

const hydro = window.OSW_HYDROGRAPHY;
const footprints = window.OSW_PROVINCE_FOOTPRINTS;
const codes = [...new Set(footprints.footprint_runs.map(run => run[3]))];
const codeIndex = new Map(codes.map((code, index) => [code, index]));
const assignments = new Int16Array(footprints.grid.shape[0] * footprints.grid.shape[1]).fill(-1);
footprints.footprint_runs.forEach(([row,start,end,code]) => assignments.fill(codeIndex.get(code),row*footprints.grid.shape[1]+start,row*footprints.grid.shape[1]+end+1));
const provinceMeta = new Map(hydro.provinces.map(item => [item.osw_code,item]));
let selectedProvince = "ANTA", selectedDepth = "0-200m", selectedMonth = "201802";

function hex(value){const clean=value.slice(1);return [parseInt(clean.slice(0,2),16),parseInt(clean.slice(2,4),16),parseInt(clean.slice(4,6),16)];}
function mix(a,b,t){return a.map((v,i)=>Math.round(v+(b[i]-v)*t));}
function temperatureColor(value){const stops=[[-2,"#315a7b"],[2,"#66aaa9"],[6,"#d7c36a"],[10,"#df865d"],[16,"#a83d42"]];if(value<=stops[0][0])return hex(stops[0][1]);for(let i=1;i<stops.length;i+=1){if(value<=stops[i][0])return mix(hex(stops[i-1][1]),hex(stops[i][1]),(value-stops[i-1][0])/(stops[i][0]-stops[i-1][0]));}return hex(stops.at(-1)[1]);}
function record(code=selectedProvince){return hydro.property_passports.find(item=>item.address.province===code&&item.address.depth_support===selectedDepth&&item.seasonal_sample===selectedMonth);}
function mollweideSample(x,y,width,height){const rootTwo=Math.SQRT2;const theta=Math.asin(Math.max(-1,Math.min(1,(1-(y+.5)/height*2))));const cosine=Math.cos(theta);const projectedX=((x+.5)/width*2-1)*2*rootTwo;const lonR=cosine<1e-10?0:Math.PI*projectedX/(2*rootTwo*cosine);if(Math.abs(lonR)>Math.PI)return {index:-2,lon:0,lat:0};const latR=Math.asin(Math.max(-1,Math.min(1,(2*theta+Math.sin(2*theta))/Math.PI)));const lon=lonR*180/Math.PI,lat=latR*180/Math.PI;const sourceColumn=Math.round((lon-footprints.grid.longitude_start)/footprints.grid.spacing_degrees);const sourceRow=Math.round((lat-footprints.grid.latitude_start)/footprints.grid.spacing_degrees);const index=sourceRow>=0&&sourceRow<720&&sourceColumn>=0&&sourceColumn<1440?assignments[sourceRow*1440+sourceColumn]:-2;return {index,lon,lat};}
function inNativeDomain(sample){const bounds=hydro.grid.coordinate_extent_deg;return sample.lon>=bounds.west&&sample.lon<=bounds.east&&sample.lat>=bounds.south&&sample.lat<=bounds.north;}
function renderMap(canvas,type){const context=canvas.getContext("2d"),image=context.createImageData(canvas.width,canvas.height),values=new Map(hydro.provinces.map(item=>[item.osw_code,record(item.osw_code)]));for(let y=0;y<canvas.height;y+=1){for(let x=0;x<canvas.width;x+=1){const sample=mollweideSample(x,y,canvas.width,canvas.height),index=sample.index,offset=(y*canvas.width+x)*4;let rgb=hex("#f8f8f4");if(index>=0){const code=codes[index],item=values.get(code),supported=item&&inNativeDomain(sample);if(type==="property")rgb=supported?temperatureColor(item.distribution.median_degC):hex("#e1e4df");else if(supported){rgb=((x+y)%9<2)?hex("#486f70"):hex("#a9ddd4");}else rgb=hex("#e1e4df");const east=x+1<canvas.width?mollweideSample(x+1,y,canvas.width,canvas.height).index:-2,south=y+1<canvas.height?mollweideSample(x,y+1,canvas.width,canvas.height).index:-2;if(east!==index||south!==index)rgb=code===selectedProvince&&inNativeDomain(sample)?hex("#9a6410"):hex("#839694");}image.data[offset]=rgb[0];image.data[offset+1]=rgb[1];image.data[offset+2]=rgb[2];image.data[offset+3]=255;}}context.putImageData(image,0,0);const chosen=record();canvas.setAttribute("aria-label",type==="property"?`Oceanic Mollweide map of the bounded Drake native-grid support only, colored by model-screen median potential temperature for ${selectedDepth} in ${selectedMonth}. ${selectedProvince} is selected at ${chosen?.distribution.median_degC ?? "no supported"} degrees Celsius.`:`Coverage map for the bounded Drake native-grid support only. Six provinces have complete native temperature samples in the subset; formal uncertainty is not estimated for any province.`);}
function option(value,label=value){const item=document.createElement("option");item.value=value;item.textContent=label;return item;}
function setup(){const province=document.querySelector("#province-select"),depth=document.querySelector("#depth-select"),month=document.querySelector("#month-select");hydro.provinces.forEach(item=>province.append(option(item.osw_code,`${item.osw_code} · ${item.source_name.replace(/^[^-]+ - /,"")}`)));hydro.depth_bands.forEach(item=>depth.append(option(item.id)));hydro.time_support.months.forEach(item=>month.append(option(item,`${item.slice(0,4)}-${item.slice(4)}`)));province.addEventListener("change",()=>{selectedProvince=province.value;render();});depth.addEventListener("change",()=>{selectedDepth=depth.value;render();});month.addEventListener("change",()=>{selectedMonth=month.value;render();});document.querySelector("#reset").addEventListener("click",()=>{selectedProvince="ANTA";selectedDepth="0-200m";selectedMonth="201802";render();});const params=new URLSearchParams(location.search);if(provinceMeta.has(params.get("province")))selectedProvince=params.get("province");if(hydro.depth_bands.some(item=>item.id===params.get("depth")))selectedDepth=params.get("depth");if(hydro.time_support.months.includes(params.get("month")))selectedMonth=params.get("month");}
function renderPassport(item){const grid=document.querySelector("#passport-grid");grid.replaceChildren();const entries=[["State",item.address.province],["Depth",item.address.depth_support],["Month",item.seasonal_sample],["Median",`${item.distribution.median_degC.toFixed(2)} °C`],["Middle 50%",`${item.distribution.p25_degC.toFixed(2)}–${item.distribution.p75_degC.toFixed(2)} °C`],["Samples",item.support.valid_native_t_cells.toLocaleString()],["Coverage",`${(item.support.fraction*100).toFixed(1)}%`],["Evidence","model screen"],["Uncertainty","not estimated"],["Method",item.method_version]];entries.forEach(([term,value])=>{const wrap=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=term;dd.textContent=value;wrap.append(dt,dd);grid.append(wrap);});const scale=value=>Math.max(0,Math.min(100,(value+2)/18*100));document.querySelector("#range-iqr").style.cssText=`left:${scale(item.distribution.p25_degC)}%;width:${scale(item.distribution.p75_degC)-scale(item.distribution.p25_degC)}%`;document.querySelector("#range-median").style.left=`${scale(item.distribution.median_degC)}%`;document.querySelector("#range-label").textContent=`p10 ${item.distribution.p10_degC.toFixed(2)} °C · median ${item.distribution.median_degC.toFixed(2)} °C · p90 ${item.distribution.p90_degC.toFixed(2)} °C`;document.querySelector("#live-summary").textContent=`${item.address.province}, ${item.address.depth_support}, ${item.seasonal_sample}: median potential temperature ${item.distribution.median_degC.toFixed(2)} °C across ${item.support.valid_native_t_cells.toLocaleString()} unweighted native samples. Coverage is ${(item.support.fraction*100).toFixed(1)}%. Uncertainty is not estimated.`;}
function renderContrasts(){const body=document.querySelector("#contrast-body");body.replaceChildren();const rows=hydro.adjacent_contrasts.filter(item=>item.provinces.includes(selectedProvince)&&item.depth_support===selectedDepth&&item.seasonal_sample===selectedMonth);if(!rows.length){const row=document.createElement("tr"),cell=document.createElement("td");cell.colSpan=6;cell.textContent="No supported adjacent-state contrast at this address.";row.append(cell);body.append(row);return;}rows.forEach(item=>{const neighbor=item.provinces.find(code=>code!==selectedProvince),sign=item.provinces[0]===selectedProvince?1:-1;const values=[item.edge_id,neighbor,`${(sign*item.first_minus_second_median_degC).toFixed(2)} °C`,item.standardized_mean_difference===null?"not defined":(sign*item.standardized_mean_difference).toFixed(2),`${item.interquartile_overlap_degC.toFixed(2)} °C`,"descriptive model screen"];const row=document.createElement("tr");values.forEach(value=>{const cell=document.createElement("td");cell.textContent=value;row.append(cell);});body.append(row);});}
function renderStateTable(){const body=document.querySelector("#state-body");body.replaceChildren();hydro.provinces.forEach(province=>{const item=record(province.osw_code);if(!item)return;const values=[province.osw_code,`${item.distribution.median_degC.toFixed(2)} °C`,`${item.distribution.p25_degC.toFixed(2)}–${item.distribution.p75_degC.toFixed(2)} °C`,item.support.valid_native_t_cells.toLocaleString(),`${(item.support.fraction*100).toFixed(1)}%`,"not estimated"];const row=document.createElement("tr");values.forEach(value=>{const cell=document.createElement("td");cell.textContent=value;row.append(cell);});body.append(row);});}
function render(){document.querySelector("#province-select").value=selectedProvince;document.querySelector("#depth-select").value=selectedDepth;document.querySelector("#month-select").value=selectedMonth;const previous=new URLSearchParams(location.search),params=new URLSearchParams({province:selectedProvince,depth:selectedDepth,month:selectedMonth});["stage","edge","filter"].forEach(key=>{if(previous.has(key))params.set(key,previous.get(key));});history.replaceState(null,"",`?${params}`);const item=record();document.querySelector("#property-caption").textContent=`${selectedMonth} · ${selectedDepth}`;renderMap(document.querySelector("#property-map"),"property");renderMap(document.querySelector("#support-map"),"support");if(item)renderPassport(item);renderStateTable();renderContrasts();}

document.querySelector("#temperature-legend").replaceChildren(...[[-2,"≤−2"],[2,"2"],[6,"6"],[10,"10"],[16,"≥16 °C"]].map(([value,label])=>{const span=document.createElement("span"),swatch=document.createElement("i");swatch.style.background=`rgb(${temperatureColor(value).join(",")})`;span.append(swatch,document.createTextNode(label));return span;}));
hydro.unsupported_properties.forEach(item=>{const li=document.createElement("li");li.textContent=`${item.property}: ${item.reason}`;document.querySelector("#unsupported-list").append(li);});
setup();render();
