"""Build the static OSW ocean-object matrix from the controlled registry."""

from collections import Counter, defaultdict
import csv
from html import escape
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "research" / "ocean-object-classification.csv"
SVG = ROOT / "figures" / "osw-ocean-object-matrix.svg"
SUMMARY = ROOT / "research" / "ocean-object-matrix-summary.json"

TYPE_META = (
    ("material_body", "Material body", "Which material?"),
    ("layer_interface", "Layer / interface", "Which vertical layer?"),
    ("gradient_boundary", "Gradient boundary", "Where does property change?"),
    ("contact_boundary", "Contact boundary", "Where do materials meet?"),
    ("flow_structure", "Flow structure", "Which velocity pattern?"),
    ("connectivity_structure", "Connectivity", "What stays connected?"),
    ("flux_budget_construct", "Flux / budget", "What crosses or fills?"),
    ("process", "Process", "What transforms?"),
    ("event_classified_state", "Event / state", "Which rule is met?"),
    ("reference_geography", "Reference geography", "Which indexing rule?"),
    ("substrate_feature", "Substrate", "Which terrain constrains?"),
    ("wave_oscillation", "Wave / oscillation", "Which phase repeats?"),
    ("phase_cover_object", "Phase / cover", "What covers or roofs?"),
)

ACCENTS = ("#67e4da", "#9ad8ff", "#ffd166", "#ff9f80", "#b7a7ff")


def load_rows(path=REGISTRY):
    with Path(path).open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if len({row["object_id"] for row in rows}) != len(rows):
        raise ValueError("duplicate object ID")
    if len({row["preferred_name"].casefold() for row in rows}) != len(rows):
        raise ValueError("duplicate object name")
    known = {key for key, _, _ in TYPE_META}
    unknown = {row["object_type"] for row in rows} - known
    if unknown:
        raise ValueError(f"unknown object types: {sorted(unknown)}")
    return sorted(rows, key=lambda row: row["object_id"])


def summarize(rows):
    by_type = Counter(row["object_type"] for row in rows)
    identities = defaultdict(Counter)
    for row in rows:
        identities[row["identity_test"]][row["object_type"]] += 1
    return {
        "schema": "osw-ocean-object-matrix-summary-v1",
        "object_count": len(rows),
        "type_count": len(TYPE_META),
        "type_order": [key for key, _, _ in TYPE_META],
        "counts_by_type": {key: by_type[key] for key, _, _ in TYPE_META},
        "identity_tests": {
            identity: {key: counts[key] for key, _, _ in TYPE_META if counts[key]}
            for identity, counts in sorted(identities.items())
        },
    }


def svg_text(x, y, text, css="label", anchor=None):
    extra = f' text-anchor="{anchor}"' if anchor else ""
    return f'<text class="{css}" x="{x}" y="{y}"{extra}>{escape(str(text))}</text>'


def render_svg(summary):
    counts = summary["counts_by_type"]
    identities = list(summary["identity_tests"])
    parts = [f'''<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1100" viewBox="0 0 1600 1100" role="img" aria-labelledby="title desc">
  <title id="title">OSW ocean-object evidence matrix</title>
  <desc id="desc">A conceptual decision ladder, thirteen equal ontology cards, and an identity-test matrix summarize 110 classified ocean objects. Counts describe this editorial registry, not natural abundance, area, importance, or certainty. Guide 13 is the complete textual equivalent.</desc>
  <metadata>Generated by analysis/build_ocean_object_matrix.py from research/ocean-object-classification.csv. Do not hand edit.</metadata>
  <style>
    text {{ font-family: Inter, ui-sans-serif, system-ui, sans-serif; }}
    .eyebrow {{ fill:#67e4da; font-size:15px; font-weight:800; letter-spacing:3px; }}
    .title {{ fill:#f4fbfa; font-size:38px; font-weight:800; }}
    .subtitle {{ fill:#a9c7c7; font-size:16px; }}
    .step {{ fill:#102b34; stroke:#52777d; stroke-width:2; }}
    .step-title {{ fill:#f4fbfa; font-size:16px; font-weight:750; }}
    .step-sub {{ fill:#a9c7c7; font-size:14px; }}
    .card {{ fill:#0c252e; stroke-width:2; }}
    .card-title {{ fill:#f4fbfa; font-size:15px; font-weight:750; }}
    .card-q {{ fill:#aac6c7; font-size:14px; }}
    .count {{ fill:#06171c; font-size:15px; font-weight:900; text-anchor:middle; }}
    .section {{ fill:#ffd166; font-size:14px; font-weight:800; letter-spacing:2px; }}
    .row {{ fill:#b8d0d0; font-size:14px; }}
    .dot {{ stroke:#06171c; stroke-width:1; }}
    .foot {{ fill:#8ca8aa; font-size:14px; }}
  </style>
  <rect width="1600" height="1100" fill="#06171c"/>
  <g role="group" aria-label="Title and evidence warning">
    <text class="eyebrow" x="64" y="48">OSW / OBJECT GRAMMAR</text>
    <text class="title" x="64" y="91">What kind of ocean thing is this?</text>
    <text class="subtitle" x="64" y="121">110 editorial terms · 13 types · one primary identity test per object</text>
    <text class="subtitle" x="1536" y="48" text-anchor="end">CONCEPTUAL MATRIX · NOT A MAP OR NATURAL HIERARCHY</text>
  </g>''']

    steps = (
        ("1  MEASURE", "property · velocity · phase · terrain"),
        ("2  ORGANIZE", "body · layer · boundary · flow"),
        ("3  CLASSIFY", "event · reference geography"),
        ("4  INTEGRATE", "pool · control volume"),
        ("5  CROSS", "boundary flux · transport"),
    )
    parts.append('<g role="group" aria-label="Five-step evidence ladder">')
    for i, (title, sub) in enumerate(steps):
        x = 64 + i * 298
        parts.append(f'<rect class="step" x="{x}" y="150" width="270" height="78" rx="14"/>')
        parts.append(svg_text(x + 18, 180, title, "step-title"))
        parts.append(svg_text(x + 18, 205, sub, "step-sub"))
        if i < 4:
            parts.append(svg_text(x + 281, 195, "→", "subtitle", "middle"))
    parts.append('</g>')

    parts.append('<g role="group" aria-label="Thirteen ocean object type cards">')
    parts.append(svg_text(64, 270, "13 PRIMARY TYPES", "section"))
    for i, (key, label, question) in enumerate(TYPE_META):
        row, col = divmod(i, 7)
        x, y = 64 + col * 216, 292 + row * 112
        accent = ACCENTS[i % len(ACCENTS)]
        parts.append(f'<g role="group" aria-label="{escape(label)}: {counts[key]} objects">')
        parts.append(f'<rect class="card" x="{x}" y="{y}" width="198" height="92" rx="12" stroke="{accent}"/>')
        parts.append(f'<circle cx="{x+172}" cy="{y+22}" r="15" fill="{accent}"/>')
        parts.append(svg_text(x + 172, y + 27, counts[key], "count", "middle"))
        parts.append(svg_text(x + 14, y + 30, label, "card-title"))
        parts.append(svg_text(x + 14, y + 57, question, "card-q"))
        parts.append('</g>')
    parts.append('</g>')

    matrix_y = 548
    parts.append('<g role="group" aria-label="Identity test by primary type matrix">')
    parts.append(svg_text(64, matrix_y, "IDENTITY TEST × PRIMARY TYPE", "section"))
    parts.append(svg_text(1536, matrix_y, "dot = at least one registry object", "foot", "end"))
    col_x = [370 + i * 88 for i in range(len(TYPE_META))]
    headers = ("BODY", "LAYER", "GRADIENT", "CONTACT", "FLOW", "CONNECT", "BUDGET", "PROCESS", "EVENT", "GEO", "SUBSTRATE", "WAVE", "COVER")
    for i, short in enumerate(headers):
        parts.append(svg_text(col_x[i], matrix_y + 30, short, "row", "middle"))
    for r, identity in enumerate(identities):
        y = matrix_y + 55 + r * 18
        parts.append(svg_text(64, y, identity.replace("_", " "), "row"))
        counts_for_identity = summary["identity_tests"][identity]
        for i, (key, _, _) in enumerate(TYPE_META):
            if key in counts_for_identity:
                accent = ACCENTS[i % len(ACCENTS)]
                parts.append(f'<circle class="dot" cx="{col_x[i]}" cy="{y-4}" r="5" fill="{accent}" aria-label="{escape(identity)} used by {escape(key)}"/>')
    parts.append('</g>')
    parts.append('''<g role="group" aria-label="Interpretation warning">
    <text class="foot" x="64" y="1070">Counts are registry coverage—not prevalence, area, importance, certainty, or a claim that nature contains exactly 110 objects.</text>
    <text class="foot" x="1536" y="1070" text-anchor="end">Complete text alternative: guides/13-HOW-TO-NAME-AN-OCEAN-PATCH.md</text>
  </g>
</svg>
''')
    return "\n".join(parts)


def build(svg_path=SVG, summary_path=SUMMARY):
    summary = summarize(load_rows())
    Path(summary_path).write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8", newline="\n")
    Path(svg_path).write_text(render_svg(summary), encoding="utf-8", newline="\n")
    return summary


if __name__ == "__main__":
    result = build()
    print(f"wrote {result['object_count']} objects across {result['type_count']} types")
