"""Package one public NOAA ERDDAP OSCAR historical surface-current pilot.

This source is the older third-degree, 5-day OSCAR archive ending in 2018. It
exists to test OSW's motion grammar without authentication; it must not be
presented as the current OSCAR v2.0 product or as ocean heat transport.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import hashlib
import io
import json
import math
import pathlib
import urllib.parse
import urllib.request


DATASET_ID = "yearly_336c_0b32_9cd3"
ERDDAP = "https://oceanwatch.pifsc.noaa.gov/erddap/griddap"
INFO_URL = f"https://oceanwatch.pifsc.noaa.gov/erddap/info/{DATASET_ID}/index.html"
DEFAULT_DATE = "2018-11-16"
DEFAULT_STRIDE = 16


def build_query(date: str, stride: int) -> str:
    dt.date.fromisoformat(date)
    if stride < 1:
        raise ValueError("stride must be positive")
    support = f"[({date}T00:00:00Z)][(15)][(80):{stride}:(-80)][(20):{stride}:(379.6666667)]"
    constraint = f"u{support},v{support}"
    return f"{ERDDAP}/{DATASET_ID}.csv0?{urllib.parse.quote(constraint, safe='():,.-')}"


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "OSW/0.1 (public research atlas)"})
    with urllib.request.urlopen(request, timeout=180) as response:
        return response.read()


def package(raw: bytes, date: str, stride: int, retrieved_at: str, query_url: str) -> dict:
    records: list[tuple[float, float, int | None, int | None]] = []
    for row in csv.reader(io.StringIO(raw.decode("utf-8"))):
        if len(row) != 6:
            raise ValueError(f"expected six ERDDAP columns, got {len(row)}")
        latitude, longitude = float(row[2]), float(row[3])
        u_number, v_number = float(row[4]), float(row[5])
        if math.isnan(u_number) or math.isnan(v_number):
            u_value = v_value = None
        else:
            u_value, v_value = round(u_number * 1000), round(v_number * 1000)
        records.append((latitude, longitude, u_value, v_value))
    latitudes = list(dict.fromkeys(record[0] for record in records))
    longitudes = list(dict.fromkeys(record[1] for record in records))
    if len(records) != len(latitudes) * len(longitudes):
        raise ValueError("historical OSCAR response is not a rectangular grid")
    u_values = [record[2] for record in records]
    v_values = [record[3] for record in records]
    valid_speeds = [
        math.hypot(u / 1000, v / 1000)
        for u, v in zip(u_values, v_values)
        if u is not None and v is not None
    ]
    if not valid_speeds:
        raise ValueError("historical OSCAR response contains no valid velocities")
    return {
        "schema": "oceanlines.oscar.historical-pilot.v1",
        "status": "historical modeled satellite-informed surface-velocity pilot",
        "source": "NOAA PIFSC ERDDAP mirror of ESR OSCAR third-degree 5-day archive",
        "dataset_id": DATASET_ID,
        "source_version": "2017.0",
        "source_coverage": "1992-10-21 through 2018-11-21",
        "source_info_url": INFO_URL,
        "date": date,
        "retrieved_at": retrieved_at,
        "query_url": query_url,
        "source_sha256": hashlib.sha256(raw).hexdigest(),
        "variables": {"u": "Ocean Surface Zonal Currents", "v": "Ocean Surface Meridional Currents"},
        "units": "m s-1",
        "stored_units": "mm s-1",
        "precision": 0.001,
        "nominal_depth_m": 15,
        "display_stride": stride,
        "native_resolution_degrees": 1 / 3,
        "shape": [len(latitudes), len(longitudes)],
        "latitude_values": latitudes,
        "longitude_values": longitudes,
        "u_mm_s": u_values,
        "v_mm_s": v_values,
        "summary": {
            "cells": len(records),
            "valid_ocean_cells": len(valid_speeds),
            "missing_or_land_cells": len(records) - len(valid_speeds),
            "minimum_speed_m_s": min(valid_speeds),
            "maximum_speed_m_s": max(valid_speeds),
        },
        "source_data_terms": "NOAA ERDDAP metadata permits free use and redistribution with accuracy and fitness disclaimers.",
        "boundary": (
            "Historical OSCAR third-degree 5-day product, version 2017.0, nominal depth 15 m. "
            "This pilot is not OSCAR v2.0, a full-depth current field, a parcel trajectory, "
            "or ocean heat transport."
        ),
    }


def write_artifact(payload: dict, output: pathlib.Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "// Generated by analysis/fetch_oscar_historical_pilot.py; do not edit by hand.\n"
        f"window.OSW_OSCAR_HISTORICAL={json.dumps(payload, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8", newline="\n",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--date", default=DEFAULT_DATE)
    parser.add_argument("--stride", type=int, default=DEFAULT_STRIDE)
    parser.add_argument("--retrieved-at")
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path("atlas/data/oscar-historical-2018-11-16.js"))
    args = parser.parse_args()
    query_url = build_query(args.date, args.stride)
    retrieved_at = args.retrieved_at or dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    payload = package(fetch(query_url), args.date, args.stride, retrieved_at, query_url)
    write_artifact(payload, args.output)
    print(f"wrote {args.output} ({payload['shape'][0]} x {payload['shape'][1]} cells)")
    print(f"source sha256 {payload['source_sha256']}")


if __name__ == "__main__":
    main()

