import importlib.util
import json
import pathlib
import tempfile
import unittest


MODULE_PATH = pathlib.Path(__file__).with_name("fetch_oscar_snapshot.py")
SPEC = importlib.util.spec_from_file_location("fetch_oscar_snapshot", MODULE_PATH)
oscar = importlib.util.module_from_spec(SPEC)
assert SPEC.loader
SPEC.loader.exec_module(oscar)


class OscarSnapshotTests(unittest.TestCase):
    def make_netcdf(self) -> bytes:
        try:
            import numpy as np
            from netCDF4 import Dataset
        except ImportError as error:
            self.skipTest(f"observation dependencies unavailable: {error}")
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "oscar.nc"
            with Dataset(path, "w") as dataset:
                dataset.createDimension("time", 1)
                dataset.createDimension("latitude", 4)
                dataset.createDimension("longitude", 6)
                dataset.createVariable("latitude", "f4", ("latitude",))[:] = [-30, -10, 10, 30]
                dataset.createVariable("longitude", "f4", ("longitude",))[:] = [0, 60, 120, 180, 240, 300]
                u = dataset.createVariable("u", "f4", ("time", "latitude", "longitude"), fill_value=-9999)
                v = dataset.createVariable("v", "f4", ("time", "latitude", "longitude"), fill_value=-9999)
                u[:] = np.arange(24, dtype="f4").reshape(1, 4, 6) / 100
                v[:] = -np.arange(24, dtype="f4").reshape(1, 4, 6) / 200
                u[0, 2, 2] = -9999
                v[0, 2, 2] = -9999
            return path.read_bytes()

    def test_cmr_query_is_exact_day_and_collection(self):
        query = oscar.build_cmr_query("2025-01-02")
        self.assertIn("C2098858642-POCLOUD", query)
        self.assertIn("2025-01-02T00%3A00%3A00Z", query)
        self.assertIn("2025-01-02T23%3A59%3A59Z", query)

    def test_package_quantizes_vectors_and_preserves_masks(self):
        payload = oscar.package(
            self.make_netcdf(), "2025-01-01", 2, "2026-08-29T00:00:00Z",
            "oscar_currents_final_20250101", "https://example.test/granule.nc",
            "https://example.test/cmr",
        )
        self.assertEqual([2, 3], payload["shape"])
        self.assertEqual([-30.0, 10.0], payload["latitude_values"])
        self.assertEqual([0.0, 120.0, 240.0], payload["longitude_values"])
        self.assertEqual(0, payload["u_mm_s"][0])
        self.assertEqual(-20, payload["v_mm_s"][2])
        self.assertIsNone(payload["u_mm_s"][4])
        self.assertIsNone(payload["v_mm_s"][4])
        self.assertEqual(30, payload["assumed_mixed_layer_depth_m"])
        self.assertIn("not full-depth velocity", payload["boundary"])
        self.assertEqual(64, len(payload["source_sha256"]))

    def test_write_artifact_has_stable_window(self):
        payload = oscar.package(
            self.make_netcdf(), "2025-01-01", 2, "2026-08-29T00:00:00Z",
            "test", "https://example.test/granule.nc", "https://example.test/cmr",
        )
        with tempfile.TemporaryDirectory() as directory:
            output = pathlib.Path(directory) / "snapshot.js"
            oscar.write_artifact(payload, output)
            text = output.read_text(encoding="utf-8")
            self.assertTrue(text.startswith("// Generated by analysis/fetch_oscar_snapshot.py"))
            encoded = text.split("=", 1)[1].rstrip(";\n")
            self.assertEqual(payload["granule_id"], json.loads(encoded)["granule_id"])


if __name__ == "__main__":
    unittest.main()

